### ISSUE TITLE
Configuration pane doesn't load

### ISSUE THREAD

**Issue by helpdsp** [wictorwilen/spfxinteams#1]
I followed all the steps described to provision your example in my tenant. Everything behaves as expected except that when adding the app as a Tab in teams the config pane doesn't show up, any hint?

![spfxissue](https://user-images.githubusercontent.com/7585891/47759963-59bf7400-dc6f-11e8-8afa-99502ca0777d.png)

**Comment by wictorwilen** [comment]
This is a known issue now - and this is just a preview. Updates and official documentation will come soon.
